
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hooper-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - frontend
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hooper-frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:80"
    restart: always
