name: hooper
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - fastapi
  - uvicorn
  - sqlalchemy
  - python-dotenv
  - tqdm
  - click
  - openai
  - pip:
      - svix
      - clerk-backend-api
      - pydantic
      - pyjwt
      - python-dateutil
      - nba_api
